Add version 2.0 with automated deployment indicators

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -63,3 +63,71 @@ jobs:
           build.workflow=${{ github.workflow }}
           build.run_id=${{ github.run_id }}
           build.run_number=${{ github.run_number }}
+
+  Deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    
+    steps: 
+      - name: config AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
+
+      - name: Deployment via SSM
+        env:
+          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
+          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/cs6620-app:latest
+        
+        run: |
+          aws ssm send-command \
+            --instance-ids "$INSTANCE_ID" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{
+              "commands": [
+                "docker pull '"$IMAGE"'",
+                "docker stop cs6620-app || true",
+                "docker rm cs6620-app || true",
+                "docker run -d --name cs6620-app -p 80:5000 --restart unless-stopped '"$IMAGE"'"
+              ]
+            }' \
+            --output json > send-command.json
+
+
+      - name: Confirm deployment status
+        env:
+          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
+        run: |
+          COMMAND_ID=$(jq -r '.Command.CommandId' send-command.json)
+          echo "Command ID: $COMMAND_ID"
+          if [ -z "$COMMAND_ID" ]; then
+            echo " Failed to obtain Command ID."
+            exit 1
+          fi
+
+          for i in {1..3}; do
+            STATUS=$(aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "$INSTANCE_ID" \
+              --query 'Status' \
+              --output text 2>/dev/null || echo "Unknown")
+            echo "Attempt $i: Status = $STATUS"
+
+            if [ "$STATUS" = "Success" ]; then
+              echo "Deployment succeeded!"
+              exit 0
+            fi
+
+            if [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
+              echo "Deployment failed with status: $STATUS"
+              exit 1
+            fi
+
+            sleep 10
+          done
+          echo "Warning: Deployment still InProgress after 3 checks. Please verify manually in AWS Systems Manager."
+          exit 0
+        
